#!/usr/bin/env python3

"""
Generate `src/generated_review_prompt_templates.rs` from Codex upstream
`codex-rs/core/src/review_prompts.rs`.

This is a manual maintenance tool. Do not call it from the app build: the
runtime Codex image is the true source of behavior, so build-time downloads do
not guarantee alignment with production.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import textwrap
import urllib.request
from pathlib import Path


UPSTREAM_REPO = "openai/codex"
UPSTREAM_PATH = "codex-rs/core/src/review_prompts.rs"
OUTPUT_PATH = Path("src/generated_review_prompt_templates.rs")
CONSTANT_NAMES = [
    "UNCOMMITTED_PROMPT",
    "BASE_BRANCH_PROMPT_BACKUP",
    "BASE_BRANCH_PROMPT",
    "COMMIT_PROMPT_WITH_TITLE",
    "COMMIT_PROMPT",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument(
        "--local-repo",
        help="Read prompt templates from a local Codex checkout.",
    )
    source.add_argument(
        "--ref",
        help="Download prompt templates from a GitHub ref in openai/codex.",
    )
    parser.add_argument(
        "--output",
        default=str(OUTPUT_PATH),
        help="Output Rust file path.",
    )
    return parser.parse_args()


def read_local_repo(repo_path: Path) -> tuple[str, str]:
    source_path = repo_path / UPSTREAM_PATH
    text = source_path.read_text(encoding="utf-8")
    commit = (
        subprocess.run(
            ["git", "-C", str(repo_path), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
        .stdout.strip()
    )
    return text, commit


def download_ref(ref: str) -> tuple[str, str]:
    url = f"https://raw.githubusercontent.com/{UPSTREAM_REPO}/{ref}/{UPSTREAM_PATH}"
    with urllib.request.urlopen(url) as response:
        text = response.read().decode("utf-8")
    return text, ref


def extract_constants(source_text: str) -> dict[str, str]:
    constants: dict[str, str] = {}
    for name in CONSTANT_NAMES:
        pattern = re.compile(
            rf'const {name}: &str =\s*"(?P<value>(?:\\.|[^"\\])*)";',
            re.MULTILINE | re.DOTALL,
        )
        match = pattern.search(source_text)
        if not match:
            raise SystemExit(f"failed to locate {name} in upstream review_prompts.rs")
        raw_value = match.group("value")
        constants[name] = bytes(raw_value, "utf-8").decode("unicode_escape")
    return constants


def generate_rust_source(source_commit: str, constants: dict[str, str]) -> str:
    metadata = {
        "repo": UPSTREAM_REPO,
        "path": UPSTREAM_PATH,
        "commit": source_commit,
    }
    metadata_json = json.dumps(metadata, indent=2)
    lines = [
        "#![allow(dead_code)]",
        "",
        "// @generated by scripts/sync_codex_review_prompts.py",
        "//",
        "// Drift note:",
        f"// - Upstream repo: {UPSTREAM_REPO}",
        f"// - Upstream path: {UPSTREAM_PATH}",
        f"// - Upstream commit/ref: {source_commit}",
        "// - This file mirrors only review target prompt templates, not Codex's",
        "//   baked review rubric from `codex-rs/core/src/tasks/review.rs`.",
        "",
        "pub(crate) const SOURCE_REPO: &str = "
        f"{json.dumps(UPSTREAM_REPO)};",
        "pub(crate) const SOURCE_PATH: &str = "
        f"{json.dumps(UPSTREAM_PATH)};",
        "pub(crate) const SOURCE_COMMIT: &str = "
        f"{json.dumps(source_commit)};",
        "",
        "pub(crate) const SOURCE_METADATA_JSON: &str = "
        f"{json.dumps(metadata_json)};",
        "",
    ]
    for name in CONSTANT_NAMES:
        value = json.dumps(constants[name])
        lines.append(f"pub(crate) const {name}: &str = {value};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    if args.local_repo:
        source_text, source_commit = read_local_repo(Path(args.local_repo))
    else:
        source_text, source_commit = download_ref(args.ref)
    constants = extract_constants(source_text)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_rust_source(source_commit, constants), encoding="utf-8")
    rel_path = output_path.as_posix()
    print(
        textwrap.dedent(
            f"""\
            wrote {rel_path}
            source repo: {UPSTREAM_REPO}
            source path: {UPSTREAM_PATH}
            source commit/ref: {source_commit}
            """
        ).strip()
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
