#![allow(dead_code)]

// @generated by scripts/sync_codex_review_prompts.py
//
// Drift note:
// - Upstream repo: openai/codex
// - Upstream path: codex-rs/core/src/review_prompts.rs
// - Upstream commit/ref: 2bc3e52a91bb88a0e067a95f8f8559f8711d30e6
// - This file mirrors only review target prompt templates, not Codex's
//   baked review rubric from `codex-rs/core/src/tasks/review.rs`.

pub(crate) const SOURCE_REPO: &str = "openai/codex";
pub(crate) const SOURCE_PATH: &str = "codex-rs/core/src/review_prompts.rs";
pub(crate) const SOURCE_COMMIT: &str = "2bc3e52a91bb88a0e067a95f8f8559f8711d30e6";

pub(crate) const SOURCE_METADATA_JSON: &str = "{\n  \"repo\": \"openai/codex\",\n  \"path\": \"codex-rs/core/src/review_prompts.rs\",\n  \"commit\": \"2bc3e52a91bb88a0e067a95f8f8559f8711d30e6\"\n}";

pub(crate) const UNCOMMITTED_PROMPT: &str = "Review the current code changes (staged, unstaged, and untracked files) and provide prioritized findings.";
pub(crate) const BASE_BRANCH_PROMPT_BACKUP: &str = "Review the code changes against the base branch '{branch}'. Start by finding the merge diff between the current branch and {branch}'s upstream e.g. (`git merge-base HEAD \"$(git rev-parse --abbrev-ref \"{branch}@{upstream}\")\"`), then run `git diff` against that SHA to see what changes we would merge into the {branch} branch. Provide prioritized, actionable findings.";
pub(crate) const BASE_BRANCH_PROMPT: &str = "Review the code changes against the base branch '{baseBranch}'. The merge base commit for this comparison is {mergeBaseSha}. Run `git diff {mergeBaseSha}` to inspect the changes relative to {baseBranch}. Provide prioritized, actionable findings.";
pub(crate) const COMMIT_PROMPT_WITH_TITLE: &str = "Review the code changes introduced by commit {sha} (\"{title}\"). Provide prioritized, actionable findings.";
pub(crate) const COMMIT_PROMPT: &str =
    "Review the code changes introduced by commit {sha}. Provide prioritized, actionable findings.";
