#![allow(dead_code)]

// @generated by scripts/sync_codex_review_prompts.py
//
// Drift note:
// - Upstream repo: openai/codex
// - Upstream path: codex-rs/prompts/src/review_request.rs
// - Upstream commit/ref: 01fc69f4026735edfdf6789820549727a4867b11
// - This file mirrors only review target prompt templates, not Codex's
//   baked review rubric from `codex-rs/prompts/templates/review/rubric.md`.

pub(crate) const SOURCE_REPO: &str = "openai/codex";
pub(crate) const SOURCE_PATH: &str = "codex-rs/prompts/src/review_request.rs";
pub(crate) const SOURCE_COMMIT: &str = "01fc69f4026735edfdf6789820549727a4867b11";

pub(crate) const SOURCE_METADATA_JSON: &str = "{\n  \"repo\": \"openai/codex\",\n  \"path\": \"codex-rs/prompts/src/review_request.rs\",\n  \"commit\": \"01fc69f4026735edfdf6789820549727a4867b11\"\n}";

pub(crate) const UNCOMMITTED_PROMPT: &str = "Review the current code changes (staged, unstaged, and untracked files) and provide prioritized findings.";
pub(crate) const BASE_BRANCH_PROMPT_BACKUP: &str = "Review the code changes against the base branch '{{branch}}'. Start by finding the merge diff between the current branch and {{branch}}'s upstream e.g. (`git merge-base HEAD \"$(git rev-parse --abbrev-ref \"{{branch}}@{upstream}\")\"`), then run `git diff` against that SHA to see what changes we would merge into the {{branch}} branch. Provide prioritized, actionable findings.";
pub(crate) const BASE_BRANCH_PROMPT: &str = "Review the code changes against the base branch '{{base_branch}}'. The merge base commit for this comparison is {{merge_base_sha}}. Run `git diff {{merge_base_sha}}` to inspect the changes relative to {{base_branch}}. Provide prioritized, actionable findings.";
pub(crate) const COMMIT_PROMPT_WITH_TITLE: &str = "Review the code changes introduced by commit {{sha}} (\"{{title}}\"). Provide prioritized, actionable findings.";
pub(crate) const COMMIT_PROMPT: &str = "Review the code changes introduced by commit {{sha}}. Provide prioritized, actionable findings.";
